'use client';

import { SUPPORT_EMAIL, SUPPORT_MAILTO } from '@/config/support';
import {
    LegalPage, H2, P, UL, LI, Strong, A, Note,
    LEGAL_COMPANY, LEGAL_ENTITY, LEGAL_JURISDICTION, LEGAL_EFFECTIVE_DATE,
} from '@/components/LegalDoc';

export default function TermsPage() {
    return (
        <LegalPage
            title="Terms of Service"
            subtitle={`These terms govern your use of ${LEGAL_COMPANY}. Please read them carefully — by creating an account or using the service, you agree to be bound by them.`}
        >
            <H2>1. Who we are</H2>
            <P>
                {LEGAL_COMPANY} (&ldquo;{LEGAL_COMPANY}&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or
                &ldquo;our&rdquo;) is an AI-powered career assistant operated by {LEGAL_ENTITY}. The service
                helps you analyze job postings, parse and optimize your resume, identify gaps against role
                requirements, generate tailored cover letters, research companies, draft outreach, and track
                your applications (collectively, the &ldquo;Service&rdquo;).
            </P>
            <P>
                These Terms of Service (the &ldquo;Terms&rdquo;) form a binding agreement between you and{' '}
                {LEGAL_ENTITY}. They incorporate our{' '}
                <A href="/privacy">Privacy Policy</A> by reference.
            </P>

            <H2>2. Eligibility</H2>
            <P>
                You must be at least 18 years old (or the age of majority in your jurisdiction) and able to
                form a binding contract to use the Service. By using {LEGAL_COMPANY}, you represent that you
                meet these requirements and that the information you provide is accurate and your own.
            </P>

            <H2>3. Your account</H2>
            <P>
                You sign in using Google. You are responsible for safeguarding access to your Google account
                and for all activity that occurs under your {LEGAL_COMPANY} account. Notify us promptly at{' '}
                <A href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</A> if you believe your account has been compromised.
                You may delete your account at any time from Settings; deletion is permanent.
            </P>

            <H2>4. What you can expect from the Service</H2>
            <P>
                {LEGAL_COMPANY} uses artificial intelligence to generate analysis, scores, suggested edits,
                cover letters, company research, and outreach drafts. This output is generated by third-party
                large language models and is provided to assist you — not to replace your own judgment.
            </P>
            <Note>
                <Strong>AI output is not professional advice.</Strong> The Service does not provide legal,
                financial, immigration, or career-counseling advice, and does not guarantee interviews, job
                offers, employment, or any particular outcome. AI-generated content can be inaccurate,
                incomplete, or out of date. You are solely responsible for reviewing, verifying, and editing
                anything you rely on or submit to an employer.
            </Note>

            <H2>5. Your content</H2>
            <P>
                &ldquo;Your Content&rdquo; means the materials you provide to the Service — including resumes,
                LinkedIn exports, portfolios, job descriptions, notes, and any text you enter. As between you
                and us, you retain all rights to Your Content.
            </P>
            <P>
                You grant us a limited, non-exclusive, worldwide license to host, store, copy, process, and
                transmit Your Content solely to operate and provide the Service to you — including sending it
                to our AI providers to produce your results. We do not sell Your Content, and we do not use it
                to train AI models. See the <A href="/privacy">Privacy Policy</A> for details on how your data
                is handled and shared.
            </P>
            <P>You represent that you have the right to share Your Content and that it does not violate any law or the rights of others.</P>
            <P>
                If you connect your own AI provider account (&ldquo;bring your own key&rdquo;), you authorize us
                to use the API key you supply solely to send your requests to that provider on your behalf. We
                store your API key <Strong>encrypted at rest</Strong>, never display it back in full, and never use
                it for any purpose other than operating the Service for you; you can remove it at any time from
                Settings. You remain responsible for your provider account, for any usage and charges your
                provider bills you, and for complying with that provider&rsquo;s terms. See the{' '}
                <A href="/privacy">Privacy Policy</A> for how your key is stored and handled.
            </P>

            <H2>6. Acceptable use</H2>
            <P>You agree not to:</P>
            <UL>
                <LI>Use the Service for any unlawful, fraudulent, or deceptive purpose, including misrepresenting your qualifications or identity to employers.</LI>
                <LI>Upload content that infringes intellectual-property rights, contains malware, or includes another person&rsquo;s personal data without authorization.</LI>
                <LI>Attempt to reverse engineer, scrape, overload, disrupt, or gain unauthorized access to the Service or its underlying systems.</LI>
                <LI>Resell, sublicense, or commercially exploit the Service or its AI output except as expressly permitted.</LI>
                <LI>Circumvent usage limits or rate limits, or share a single account across multiple people.</LI>
            </UL>
            <P>We may suspend or terminate accounts that violate these rules.</P>

            <H2>7. Cost and your AI provider</H2>
            <P>
                {LEGAL_COMPANY} is free to use. We do not charge subscription fees, sell credits, or process
                payments. To generate results, the Service runs on AI providers using the API key you connect
                (&ldquo;bring your own key&rdquo;).
            </P>
            <UL>
                <LI><Strong>You pay your provider, not us.</Strong> Any costs for AI usage are billed directly to you by your chosen AI provider under your own account and that provider&rsquo;s pricing and terms. We do not mark up, collect, or receive any portion of those charges.</LI>
                <LI><Strong>Usage tracking.</Strong> We record token usage for the AI tasks you run for product analytics and to operate the Service. This is measurement only and does not result in any charge from us.</LI>
                <LI><Strong>Fair use.</Strong> We may apply reasonable rate limits to keep the Service available and to prevent abuse.</LI>
            </UL>
            <P>
                You are responsible for monitoring and managing usage and any charges on your AI provider account.
                We are not responsible for fees charged by your AI provider.
            </P>

            <H2>8. Changes to the Service</H2>
            <P>
                We are actively developing {LEGAL_COMPANY} and may add, change, or remove features at any time.
                The Service is currently provided free of charge; if we ever introduce paid features, we will
                provide reasonable notice and they will not apply to you without your consent. Continuing to use
                the Service after a change takes effect constitutes acceptance.
            </P>

            <H2>9. Intellectual property</H2>
            <P>
                The Service itself — including its software, design, branding, and content we create — is owned
                by {LEGAL_ENTITY} and protected by intellectual-property laws. We grant you a limited,
                revocable, non-transferable license to use the Service for your personal job search in
                accordance with these Terms. Subject to our rights in the underlying Service, you own the
                outputs generated for you and may use them for your own job-search purposes.
            </P>

            <H2>10. Third-party services</H2>
            <P>
                The Service relies on third parties, including Google (sign-in) and the AI providers whose API
                keys you connect (such as Anthropic, OpenAI, Google Gemini, xAI, and DeepSeek), as well as our
                hosting and infrastructure providers. Your use of those services is subject to their own terms,
                and we are not responsible for their acts or omissions.
            </P>

            <H2>11. Disclaimers</H2>
            <P>
                The Service is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties
                of any kind, whether express or implied, including implied warranties of merchantability,
                fitness for a particular purpose, accuracy, and non-infringement. We do not warrant that the
                Service will be uninterrupted, error-free, secure, or that AI output will be accurate or
                suitable for your needs.
            </P>

            <H2>12. Limitation of liability</H2>
            <P>
                To the maximum extent permitted by law, {LEGAL_ENTITY} and its operators will not be liable for
                any indirect, incidental, special, consequential, or punitive damages, or for any lost profits,
                lost opportunities, or lost or missed employment, arising out of or related to your use of the
                Service. Our total aggregate liability for any claim relating to the Service will not exceed the
                greater of (a) the amount you paid us in the twelve months before the event giving rise to the
                claim, or (b) USD&nbsp;100. Some jurisdictions do not allow certain limitations, so some of the
                above may not apply to you.
            </P>

            <H2>13. Indemnification</H2>
            <P>
                You agree to indemnify and hold harmless {LEGAL_ENTITY} and its operators from any claims,
                damages, liabilities, and expenses (including reasonable legal fees) arising from Your Content,
                your use of the Service, or your violation of these Terms or any law or third-party right.
            </P>

            <H2>14. Termination</H2>
            <P>
                You may stop using the Service and delete your account at any time. We may suspend or terminate
                your access if you violate these Terms, if required by law, or if necessary to protect the
                Service or other users. Upon termination, your right to use the Service ends. Sections that by
                their nature should survive termination (including ownership, disclaimers, limitation of
                liability, and indemnification) will survive.
            </P>

            <H2>15. Governing law and disputes</H2>
            <P>
                These Terms are governed by the laws of {LEGAL_JURISDICTION}, without regard to its conflict-of-laws
                rules. You agree to the exclusive jurisdiction of the courts located in {LEGAL_JURISDICTION} for any
                dispute that is not subject to mandatory arbitration or small-claims resolution where applicable.
            </P>

            <H2>16. Changes to these Terms</H2>
            <P>
                We may update these Terms from time to time. When we make material changes, we will update the
                &ldquo;Last updated&rdquo; date above and, where appropriate, notify you. Your continued use of
                the Service after changes take effect means you accept the revised Terms.
            </P>

            <H2>17. Contact</H2>
            <P>
                Questions about these Terms? Reach us at{' '}
                <A href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</A>. These Terms are effective as of {LEGAL_EFFECTIVE_DATE}.
            </P>
        </LegalPage>
    );
}
